#!/bin/bash

baseroot=/var/www/download.kiwix.org/nightly
today=`date +%F`

# remove old folders
find ${baseroot}/ -mindepth 1 -maxdepth 1 -type d -mtime +30 -exec rm -rf {} \;

# create today's date folder if not exist
mkdir -p ${baseroot}/${today}

# remove previous latest link
rm -f ${baseroot}/latest

# recreate symlink
ln -s ${baseroot}/${today} ${baseroot}/latest
