#!/bin/bash

baseroot=/var/www/download.kiwix.org/nightly
today=`date +%F`

# remove old folders
find ${baseroot}/ -mindepth 2 -maxdepth 2 -type d -mtime +30 -exec rm -rf {} \;

# create today's date folder if not exist
mkdir -p ${baseroot}/{src,bin}/${today}

# remove previous latest link
rm -f ${baseroot}/{src,bin}/latest

# recreate symlink
ln -s ${baseroot}/src/${today} ${baseroot}/src/latest
ln -s ${baseroot}/bin/${today} ${baseroot}/bin/latest
