#!/bin/sh

if [ -n "${APPLEPAY_MERCHANT_CERTIFICATE}" ] && [ -n "${APPLEPAY_MERCHANT_CERTIFICATE_PATH}" ] ; then
    echo "$APPLEPAY_MERCHANT_CERTIFICATE" > ${APPLEPAY_MERCHANT_CERTIFICATE_PATH}
fi

if [ -n "${APPLEPAY_MERCHANT_CERTIFICATE_KEY}" ] && [ -n "${APPLEPAY_MERCHANT_CERTIFICATE_KEY_PATH}" ] ; then
    echo "$APPLEPAY_MERCHANT_CERTIFICATE_KEY" > ${APPLEPAY_MERCHANT_CERTIFICATE_KEY_PATH}
fi

exec "$@"
