name: DNS Cache

on:
  push:
    branches:
      - 'main'
    paths:
      - 'dns-cache/**'
  workflow_dispatch:

jobs:

  donation-api:
    name: Deploy DNS Cache Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish DNS Cache Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/dns-cache
          on-master: latest
          restrict-to: kiwix/container-images
          context: dns-cache
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
