name: ftpd

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ftpd/**'
  workflow_dispatch:

jobs:

  ftpd:
    name: Deploy ftpd Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/ftpd
          on-master: latest
          restrict-to: kiwix/container-images
          context: ftpd
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
