name: Matomo

on:
  push:
    branches:
      - 'main'
    paths:
      - 'matomo/**'
  workflow_dispatch:

jobs:

  matomo:
    name: Deploy Matomo Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/matomo
          on-master: 5.3.2-fpm
          restrict-to: kiwix/container-images
          context: matomo
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
